tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "curl"
brew "dnsmasq", restart_service: true
brew "fish"
brew "git"
brew "mariadb", restart_service: true
brew "postgresql", restart_service: true
brew "pyenv"
brew "pyenv-virtualenv"
brew "redis", restart_service: true
brew "vim"
brew "wget"
brew "zlib"
brew "leipert-projects/git-recon/git-recon"
