# make tmux display things in 256 colors
# set -g default-terminal "xterm-256color"
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256col*:Tc"
set -g default-shell $SHELL

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

# set scrollback history to 30000 (30k)
set -g history-limit 30000

# make nvim not pause after hitting escape
set -sg escape-time 0

# request by :checkhealth in neovim
set-option -g focus-events on

# set window and pane index to 1 (0 by default)
set-option -g base-index 1
setw -g pane-base-index 1
# panes
# use PREFIX | to split window horizontally and PREFIX - to split vertically
bind \\ split-window -h -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -c "#{pane_current_path}"

# mouse control for tmux v2.1
set -g mouse on

# ---------------------
# Copy & Paste
# ---------------------
# use vi/vim key bindings in copy mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

# Popup selector that shows all sessions
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# Reload config
bind r source-file ~/.config/tmux/tmux.conf

set -g @catppuccin_flavour 'macchiato' # or frappe, macchiato, mocha

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'

# set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
# set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

# set -g @resurrect-capture-pane-contents 'on'
# set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
