#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Default programs:
export EDITOR="lvim"
export TERMINAL="alacritty"
export BROWSER="brave"

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_STATE_HOME="${HOME}/.local/state"

# Add all local binaries to the system path.
export PATH="$HOME/.local/bin":$PATH
# export PATH="${PATH}:${HOME}/.local/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/tools/lua-language-server/bin/macOS:$PATH"

export GOPATH="$HOME/dev/gocode" 
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

