set -g default-shell $SHELL

# Change default key binding to Ctrl + A
unbind-key C-b
set -g prefix C-a
bind-key C-a send-prefix

# use 256 term for pretty colors
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"


# Open window in current path
bind c new-window -c '#{pane_current_path}'

# Open current directory
bind o run-shell "open #{pane_current_path}"
bind -r e kill-pane -a
unbind-key x               # unbind-key “x” from it’s current job of “ask and then close”
bind-key x kill-pane       # rebind-key it to just “close”
bind-key X kill-session    # key combo for killing the entire session - <prefix> + shift + x

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# vi mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'V' send -X select-line
#bind-key -T copy-mode-vi Escape send -X cancel

bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

# decrease command delay (increases vim responsiveness)
set -sg escape-time 1

# start window index at 1
set -g base-index 1

# start pane index at 1
setw -g pane-base-index 1

# Resize panes
bind-key J resize-pane -D 10
bind-key K resize-pane -U 10
bind-key H resize-pane -L 10
bind-key L resize-pane -R 10

# Select panes 
# See to prevent cycling https://github.com/tmux/tmux/issues/1158
bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key h select-pane -L 
bind-key l select-pane -R

# Source file
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded!"

bind h set-option -g status
bind C-s set-option -g status

bind s display-popup -E -d '#{pane_current_path}' 'git status && sleep 5'

# default statusbar colors
#――――――――――――――――――――――――――――――――
set-option -g status-bg default
set-option -g status-fg colour240

# default window title colors
#―――――――――――――――――――――――――――――――
set-window-option -g window-status-style fg=magenta
set-window-option -g window-status-style bg=default

set -g status-left-length 85
set -g status-left "working on#[fg=colour135] #S"
set -g window-status-current-format "#[fg=black,bold bg=default]│#[fg=white bg=cyan]#W#[fg=black,bold bg=default]│"
set -g window-status-current-format "#[fg=black,bold bg=default]│#[fg=colour135 bg=black]#W#[fg=black,bold bg=default]│"
set -g status-style bg=default
set -g status-right "#[fg=magenta] #[bg=gray] %b %d %Y %l:%M %p"
set -g status-right '#(gitmux "#{pane_current_path}")' 
set -g status-justify centre

# custom stuff from ThePrimeagen.
bind-key -r i run-shell "tmux neww tmux-cht.sh"

bind -r D neww -c "#{pane_current_path}" "[[ -e TODO.md ]] && nvim TODO.md || nvim ~/dotfiles/todo.md"

