# vim:fileencoding=utf-8:foldmethod=marker


#:     font_family      Operator Mono Book
#:     bold_font        Operator Mono Medium
#:     italic_font      Operator Mono Book Italic
#:     bold_italic_font Operator Mono Medium Italic
font_family      MonoLisa Nerd Font Mono Regular
bold_font        MonoLisa Nerd Font Mono Bold
italic_font      MonoLisa Nerd Font Mono Italic
bold_italic_font MonoLisa Nerd Font Mono Bold Italic
# font_family      VictorMono Nerd Font Mono Regular
# bold_font        VictorMono Nerd Font Mono Bold
# italic_font      VictorMono Nerd Font Mono Italic
# bold_italic_font VictorMono Nerd Font Mono Bold Italic

font_size 18.0
sync_to_monitor no
disable_ligatures never

map ctrl+shift+q noop
map ctrl+shift+w noop
enable_audio_bell no


#map super+enter          toggle_fullscreen
#map super+n
#map super+w
#map ctrl+shift+]
#map ctrl+shift+[
#map ctrl+shift+f
#map ctrl+shift+b
#map ctrl+shift+`
#map ctrl+shift+1
#map ctrl+shift+2
#map ctrl+shift+3
#map ctrl+shift+4
#map ctrl+shift+5
#map ctrl+shift+6
#map ctrl+shift+7
#map ctrl+shift+8
#map ctrl+shift+9
#map ctrl+shift+0
#map kitty_mod+enter


tab_bar_style powerline

background #282c34

background_opacity 0.9
hide_window_decorations yes
macos_traditional_fullscreen yes

include ~/.dotfiles/kitty/themes/catppuccin.conf
