#: Fonts {{{

font_size 18.0
font_family      DankMono Nerd Font Mono
bold_font        DankMono Nerd Font Mono Bold
italic_font      DankMono Nerd Font Mono Italic

#font_family      Fira Code Retina Nerd Font Complete Mono
#italic_font      Operator Mono Book Italic Nerd Font Complete Mono
#bold_font        Operator Mono Bold Nerd Font Complete
#bold_italic_font Operator Mono Bold Italic Nerd Font Complete

#macos_thicken_font 0.7
#background_opacity 0.9
macos_option_as_alt yes
hide_window_decorations yes
enabled_layouts tall:bias=55;full_size=1,stack,fat,horizontal
window_border_width 1.0
window_margin_width 0.0
window_padding_width 0 0 0 0
macos_traditional_fullscreen yes
disable_ligatures cursor
enable_audio_bell no
enable_audio_bell no
remember_window_size no
# don't draw extra borders, but fade the inactive text a bit
active_border_color none
inactive_text_alpha 0.6
shell .


# Tab bar {{{
# Which edge to show the tab bar on, top or bottom
tab_bar_edge bottom
# The separator between tabs in the tab bar
tab_separator "|"
# Tab bar colors and styles
active_tab_foreground #000
active_tab_background #eee
active_tab_font_style bold-italic
# inactive_tab_foreground #444
# inactive_tab_background #999
# inactive_tab_font_style normal
# }}}

#  Color scheme {{{
#include ./onedark.conf
include ./catppuccin.conf
#}}}


mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url
map cmd+c        copy_to_clipboard
map cmd+v        paste_from_clipboard

# open new split (window) with cmd+d retaining the cwd
map cmd+d new_window_with_cwd

# open new tab with cmd+t
map cmd+t new_tab_with_cwd

# new split with default cwd
map cmd+shift+d new_window

# switch between next and previous splits
map cmd+]        next_window
map cmd+[        previous_window

# jump to beginning and end of word
map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# jump to beginning and end of line
map cmd+left send_text all \x01
map cmd+right send_text all \x05

# Map cmd + <num> to corresponding tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

